// *********************************************************************************************************************
// ***                                        CONFIDENTIAL --- CUSTOM STUDIOS                                        ***
// *********************************************************************************************************************
// * Auth: ColeCai                                                                                                     *
// * Date: 2024/03/10 22:39:09                                                                                         *
// * Proj: fingertge                                                                                                   *
// * Pack: inner                                                                                                       *
// * File: inner.proto                                                                                                 *
// *-------------------------------------------------------------------------------------------------------------------*
// * Overviews:                                                                                                        *
// *-------------------------------------------------------------------------------------------------------------------*
// * Functions:                                                                                                        *
// * - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - *

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.23.2
// source: inner.proto

package inner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ServiceType int32

const (
	ServiceType_SERVICE_NONE    ServiceType = 0
	ServiceType_SERVICE_CLIENT  ServiceType = 1
	ServiceType_SERVICE_ACCESS  ServiceType = 11
	ServiceType_SERVCIE_BANK    ServiceType = 12
	ServiceType_SERVCIE_USER    ServiceType = 13
	ServiceType_SERVCIE_WEBGATE ServiceType = 14
)

// Enum value maps for ServiceType.
var (
	ServiceType_name = map[int32]string{
		0:  "SERVICE_NONE",
		1:  "SERVICE_CLIENT",
		11: "SERVICE_ACCESS",
		12: "SERVCIE_BANK",
		13: "SERVCIE_USER",
		14: "SERVCIE_WEBGATE",
	}
	ServiceType_value = map[string]int32{
		"SERVICE_NONE":    0,
		"SERVICE_CLIENT":  1,
		"SERVICE_ACCESS":  11,
		"SERVCIE_BANK":    12,
		"SERVCIE_USER":    13,
		"SERVCIE_WEBGATE": 14,
	}
)

func (x ServiceType) Enum() *ServiceType {
	p := new(ServiceType)
	*p = x
	return p
}

func (x ServiceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServiceType) Descriptor() protoreflect.EnumDescriptor {
	return file_inner_proto_enumTypes[0].Descriptor()
}

func (ServiceType) Type() protoreflect.EnumType {
	return &file_inner_proto_enumTypes[0]
}

func (x ServiceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServiceType.Descriptor instead.
func (ServiceType) EnumDescriptor() ([]byte, []int) {
	return file_inner_proto_rawDescGZIP(), []int{0}
}

type InnerMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SrcType ServiceType `protobuf:"varint,1,opt,name=src_type,json=srcType,proto3,enum=inner.ServiceType" json:"src_type,omitempty"`
	SrcSvid uint32      `protobuf:"varint,2,opt,name=src_svid,json=srcSvid,proto3" json:"src_svid,omitempty"`
	MsgName string      `protobuf:"bytes,3,opt,name=msg_name,json=msgName,proto3" json:"msg_name,omitempty"`
	MsgBody []byte      `protobuf:"bytes,4,opt,name=msg_body,json=msgBody,proto3" json:"msg_body,omitempty"`
}

func (x *InnerMsg) Reset() {
	*x = InnerMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InnerMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InnerMsg) ProtoMessage() {}

func (x *InnerMsg) ProtoReflect() protoreflect.Message {
	mi := &file_inner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InnerMsg.ProtoReflect.Descriptor instead.
func (*InnerMsg) Descriptor() ([]byte, []int) {
	return file_inner_proto_rawDescGZIP(), []int{0}
}

func (x *InnerMsg) GetSrcType() ServiceType {
	if x != nil {
		return x.SrcType
	}
	return ServiceType_SERVICE_NONE
}

func (x *InnerMsg) GetSrcSvid() uint32 {
	if x != nil {
		return x.SrcSvid
	}
	return 0
}

func (x *InnerMsg) GetMsgName() string {
	if x != nil {
		return x.MsgName
	}
	return ""
}

func (x *InnerMsg) GetMsgBody() []byte {
	if x != nil {
		return x.MsgBody
	}
	return nil
}

type WebGateMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServiceType ServiceType `protobuf:"varint,1,opt,name=service_type,json=serviceType,proto3,enum=inner.ServiceType" json:"service_type,omitempty"`
	Mode        uint64      `protobuf:"varint,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Svid        uint32      `protobuf:"varint,3,opt,name=svid,proto3" json:"svid,omitempty"`
	ReqName     string      `protobuf:"bytes,4,opt,name=req_name,json=reqName,proto3" json:"req_name,omitempty"`
	ReqBody     []byte      `protobuf:"bytes,5,opt,name=req_body,json=reqBody,proto3" json:"req_body,omitempty"`
	RspName     string      `protobuf:"bytes,6,opt,name=rsp_name,json=rspName,proto3" json:"rsp_name,omitempty"`
	RspBody     []byte      `protobuf:"bytes,7,opt,name=rsp_body,json=rspBody,proto3" json:"rsp_body,omitempty"`
}

func (x *WebGateMsg) Reset() {
	*x = WebGateMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebGateMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebGateMsg) ProtoMessage() {}

func (x *WebGateMsg) ProtoReflect() protoreflect.Message {
	mi := &file_inner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebGateMsg.ProtoReflect.Descriptor instead.
func (*WebGateMsg) Descriptor() ([]byte, []int) {
	return file_inner_proto_rawDescGZIP(), []int{1}
}

func (x *WebGateMsg) GetServiceType() ServiceType {
	if x != nil {
		return x.ServiceType
	}
	return ServiceType_SERVICE_NONE
}

func (x *WebGateMsg) GetMode() uint64 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *WebGateMsg) GetSvid() uint32 {
	if x != nil {
		return x.Svid
	}
	return 0
}

func (x *WebGateMsg) GetReqName() string {
	if x != nil {
		return x.ReqName
	}
	return ""
}

func (x *WebGateMsg) GetReqBody() []byte {
	if x != nil {
		return x.ReqBody
	}
	return nil
}

func (x *WebGateMsg) GetRspName() string {
	if x != nil {
		return x.RspName
	}
	return ""
}

func (x *WebGateMsg) GetRspBody() []byte {
	if x != nil {
		return x.RspBody
	}
	return nil
}

type GetUserInfoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetUserInfoReq) Reset() {
	*x = GetUserInfoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoReq) ProtoMessage() {}

func (x *GetUserInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_inner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoReq.ProtoReflect.Descriptor instead.
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return file_inner_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserInfoReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetUserInfoRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetUserInfoRsp) Reset() {
	*x = GetUserInfoRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserInfoRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRsp) ProtoMessage() {}

func (x *GetUserInfoRsp) ProtoReflect() protoreflect.Message {
	mi := &file_inner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRsp.ProtoReflect.Descriptor instead.
func (*GetUserInfoRsp) Descriptor() ([]byte, []int) {
	return file_inner_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserInfoRsp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetUserCoinReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid uint64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *GetUserCoinReq) Reset() {
	*x = GetUserCoinReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCoinReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCoinReq) ProtoMessage() {}

func (x *GetUserCoinReq) ProtoReflect() protoreflect.Message {
	mi := &file_inner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCoinReq.ProtoReflect.Descriptor instead.
func (*GetUserCoinReq) Descriptor() ([]byte, []int) {
	return file_inner_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserCoinReq) GetUid() uint64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

type GetUserCoinRsp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Coint uint64 `protobuf:"varint,2,opt,name=coint,proto3" json:"coint,omitempty"`
}

func (x *GetUserCoinRsp) Reset() {
	*x = GetUserCoinRsp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_inner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCoinRsp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCoinRsp) ProtoMessage() {}

func (x *GetUserCoinRsp) ProtoReflect() protoreflect.Message {
	mi := &file_inner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCoinRsp.ProtoReflect.Descriptor instead.
func (*GetUserCoinRsp) Descriptor() ([]byte, []int) {
	return file_inner_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserCoinRsp) GetCoint() uint64 {
	if x != nil {
		return x.Coint
	}
	return 0
}

var File_inner_proto protoreflect.FileDescriptor

var file_inner_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x69,
	0x6e, 0x6e, 0x65, 0x72, 0x22, 0x8a, 0x01, 0x0a, 0x08, 0x49, 0x6e, 0x6e, 0x65, 0x72, 0x4d, 0x73,
	0x67, 0x12, 0x2d, 0x0a, 0x08, 0x73, 0x72, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x07, 0x73, 0x72, 0x63, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x73, 0x72, 0x63, 0x5f, 0x73, 0x76, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x07, 0x73, 0x72, 0x63, 0x53, 0x76, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x6d,
	0x73, 0x67, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x73, 0x67, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x6d, 0x73, 0x67, 0x42, 0x6f, 0x64,
	0x79, 0x22, 0xd7, 0x01, 0x0a, 0x0a, 0x57, 0x65, 0x62, 0x47, 0x61, 0x74, 0x65, 0x4d, 0x73, 0x67,
	0x12, 0x35, 0x0a, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x12, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x04, 0x6d, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x73,
	0x76, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x76, 0x69, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x72, 0x65, 0x71, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x72, 0x65, 0x71, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x65,
	0x71, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x65,
	0x71, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x73, 0x70, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x72, 0x73, 0x70, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x72, 0x73, 0x70, 0x5f, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x72, 0x73, 0x70, 0x42, 0x6f, 0x64, 0x79, 0x22, 0x22, 0x0a, 0x0e, 0x47,
	0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22,
	0x24, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73,
	0x70, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x22, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72,
	0x43, 0x6f, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x26, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x63, 0x6f, 0x69, 0x6e,
	0x74, 0x2a, 0x80, 0x01, 0x0a, 0x0b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x10, 0x0a, 0x0c, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x4e, 0x4f, 0x4e,
	0x45, 0x10, 0x00, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x5f, 0x43,
	0x4c, 0x49, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x45, 0x52, 0x56, 0x49,
	0x43, 0x45, 0x5f, 0x41, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x0b, 0x12, 0x10, 0x0a, 0x0c, 0x53,
	0x45, 0x52, 0x56, 0x43, 0x49, 0x45, 0x5f, 0x42, 0x41, 0x4e, 0x4b, 0x10, 0x0c, 0x12, 0x10, 0x0a,
	0x0c, 0x53, 0x45, 0x52, 0x56, 0x43, 0x49, 0x45, 0x5f, 0x55, 0x53, 0x45, 0x52, 0x10, 0x0d, 0x12,
	0x13, 0x0a, 0x0f, 0x53, 0x45, 0x52, 0x56, 0x43, 0x49, 0x45, 0x5f, 0x57, 0x45, 0x42, 0x47, 0x41,
	0x54, 0x45, 0x10, 0x0e, 0x32, 0x82, 0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x12, 0x36, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x15,
	0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0b,
	0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x43, 0x6f, 0x69, 0x6e, 0x67, 0x12, 0x15, 0x2e, 0x69, 0x6e,
	0x6e, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x6f, 0x69, 0x6e, 0x52, 0x73, 0x70, 0x42, 0x16, 0x5a, 0x14, 0x2e, 0x2e, 0x2f,
	0x2e, 0x2e, 0x2f, 0x70, 0x62, 0x2f, 0x69, 0x6e, 0x6e, 0x65, 0x72, 0x3b, 0x69, 0x6e, 0x6e, 0x65,
	0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_inner_proto_rawDescOnce sync.Once
	file_inner_proto_rawDescData = file_inner_proto_rawDesc
)

func file_inner_proto_rawDescGZIP() []byte {
	file_inner_proto_rawDescOnce.Do(func() {
		file_inner_proto_rawDescData = protoimpl.X.CompressGZIP(file_inner_proto_rawDescData)
	})
	return file_inner_proto_rawDescData
}

var file_inner_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_inner_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_inner_proto_goTypes = []interface{}{
	(ServiceType)(0),       // 0: inner.ServiceType
	(*InnerMsg)(nil),       // 1: inner.InnerMsg
	(*WebGateMsg)(nil),     // 2: inner.WebGateMsg
	(*GetUserInfoReq)(nil), // 3: inner.GetUserInfoReq
	(*GetUserInfoRsp)(nil), // 4: inner.GetUserInfoRsp
	(*GetUserCoinReq)(nil), // 5: inner.GetUserCoinReq
	(*GetUserCoinRsp)(nil), // 6: inner.GetUserCoinRsp
}
var file_inner_proto_depIdxs = []int32{
	0, // 0: inner.InnerMsg.src_type:type_name -> inner.ServiceType
	0, // 1: inner.WebGateMsg.service_type:type_name -> inner.ServiceType
	3, // 2: inner.UserService.Search:input_type -> inner.GetUserInfoReq
	5, // 3: inner.UserService.SearchCoing:input_type -> inner.GetUserCoinReq
	4, // 4: inner.UserService.Search:output_type -> inner.GetUserInfoRsp
	6, // 5: inner.UserService.SearchCoing:output_type -> inner.GetUserCoinRsp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_inner_proto_init() }
func file_inner_proto_init() {
	if File_inner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_inner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InnerMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebGateMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserInfoRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCoinReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_inner_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCoinRsp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_inner_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inner_proto_goTypes,
		DependencyIndexes: file_inner_proto_depIdxs,
		EnumInfos:         file_inner_proto_enumTypes,
		MessageInfos:      file_inner_proto_msgTypes,
	}.Build()
	File_inner_proto = out.File
	file_inner_proto_rawDesc = nil
	file_inner_proto_goTypes = nil
	file_inner_proto_depIdxs = nil
}
